version: "2"

run:
  tests: true

linters:
  default: none
  enable:
    - goconst
    - gocritic
    - godot
    - govet
    - ineffassign
    - intrange
    - lll
    - misspell
    - nlreturn
    - noctx
    - revive
    - staticcheck
    - unused
    - whitespace
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        path: _test\.go
  settings:
    revive:
      rules:
        - name: var-naming
          exclude:
            - "broker/amqp/rabbit/config.go" # skip due to the big no. of constants in the file that do not have comments.
          arguments:
            - [] # AllowList
            - [] # DenyList
            - - skip-package-name-collision-with-go-std: true

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
        - pattern: 'a[b:len(a)]'
          replacement: 'a[b:]'
        - pattern: 'a[0:b]'
          replacement: 'a[:b]'
